[package]
name = "phichain-converter"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
phichain-chart = { path = "../phichain-chart" }
serde_json = "1.0.117"
strum = { version = "0.26", features = ["derive"] }
